Fix migrations and remove icon composer package
MarJose123/filament-webhook-server pull request #31
Opened 2024-07-22 10:52 UTC by Poseidon281

2024-07-23 03:44 UTC, MarJose123 commented on src/Pages/Webhooks.php
> +        return config('filament-webhook-server.navigation.icon');
Can you add some validation if the `navigation.icon` is existing in the config, and if not return the icon name instead.

2024-07-23 03:45 UTC, MarJose123 requested changes
All change is good, however I have one change request. thanks

2024-07-23 11:26 UTC, Poseidon281 reviewed
I reapplyed this commit because the TextInput causes a LiveWire issue.

2024-07-27 14:06 UTC, MarJose123 commented on src/Pages/Webhooks.php
> +                TextInput::make('description'),
Can you revert this please. thanks.

2024-07-27 18:31 UTC, Poseidon281 commented on src/Pages/Webhooks.php
> +                TextInput::make('description'),
Done

2024-07-28 10:46 UTC, merged